openapi: 3.0.3
info:
  title: Maleware Scanner - IBAN Check
  license:
    name: MIT License
    url: https://opensource.org/license/mit
  version: 1.0.0
servers:
  - url: http://localhost:8080/api/v1
tags:
  - name: Check
  - name: Utils
paths:
  /check:
    post:
      tags:
        - Check
      summary: "Check a pdf if it contains any blacklisted IBAN"
      requestBody:
        description: "Check an pdf determined by a url"
        content:
          application/json:
            schema:
              type: object
              required:
                - url
              properties:
                url:
                  type: string
                  format: url
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StateEnum'
        '400':
          description: Bad Request
        '500':
          description: Internal Server error
  /time:
    get:
      tags:
        - Utils
      summary: "Get the current application time"
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: string
                format: date-time
        '500':
          description: Internal Server error

components:
  schemas:
    StateEnum:
      type: string
      nullable: false
      enum:
        - OK
        - SUSPICIOUS
        - IGNORED
      default: SUSPICIOUS